# Generated by Django 4.2.3 on 2023-07-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contect',
            new_name='Contact',
        ),
    ]
